#!/usr/bin/env python3
import os
import json

# Define all markdown files
files = [
    'data-structures-algorithms/mid-level.md',
    'data-structures-algorithms/senior-level.md',
    'data-structures-algorithms/principal-level.md',
    'system-design/mid-level.md',
    'system-design/senior-level.md',
    'system-design/principal-level.md',
    'programming-languages/mid-level.md',
    'programming-languages/senior-level.md',
    'programming-languages/principal-level.md',
    'architecture/mid-level.md',
    'architecture/senior-level.md',
    'architecture/principal-level.md',
    'databases/mid-level.md',
    'databases/senior-level.md',
    'databases/principal-level.md',
    'devops-cloud/mid-level.md',
    'devops-cloud/senior-level.md',
    'devops-cloud/principal-level.md',
    'behavioral/mid-level.md',
    'behavioral/senior-level.md',
    'behavioral/principal-level.md'
]

materials = {}

# Read all markdown files
for filepath in files:
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            materials[filepath] = content
            print(f"✓ Loaded: {filepath}")
    except FileNotFoundError:
        print(f"✗ Not found: {filepath}")
    except Exception as e:
        print(f"✗ Error reading {filepath}: {e}")

# Generate JavaScript file
js_output = """// Materials data - Auto-generated file
// Generated by generate-materials-data.py
// This file contains all markdown content embedded for offline use

// Use window for browser, fallback to global for Node.js
(function(global) {
    const MATERIALS_DATA = """

js_output += json.dumps(materials, indent=2, ensure_ascii=False)

js_output += """;

    // Export to global scope
    global.MATERIALS_DATA = MATERIALS_DATA;

    // Also export for Node.js if available
    if (typeof module !== 'undefined' && module.exports) {
        module.exports = MATERIALS_DATA;
    }
})(typeof window !== 'undefined' ? window : global);
"""

# Write to file
with open('materials-data.js', 'w', encoding='utf-8') as f:
    f.write(js_output)

print(f"\n✅ Generated materials-data.js with {len(materials)} files")
print(f"📦 Total size: {len(js_output) / 1024:.2f} KB")
