#!/usr/bin/env python3
import os
import json

# Define all markdown files (English versions)
files_en = [
    'data-structures-algorithms/mid-level.md',
    'data-structures-algorithms/senior-level.md',
    'data-structures-algorithms/principal-level.md',
    'system-design/mid-level.md',
    'system-design/senior-level.md',
    'system-design/principal-level.md',
    'programming-languages/mid-level.md',
    'programming-languages/senior-level.md',
    'programming-languages/principal-level.md',
    'architecture/mid-level.md',
    'architecture/senior-level.md',
    'architecture/principal-level.md',
    'databases/mid-level.md',
    'databases/senior-level.md',
    'databases/principal-level.md',
    'devops-cloud/mid-level.md',
    'devops-cloud/senior-level.md',
    'devops-cloud/principal-level.md',
    'behavioral/mid-level.md',
    'behavioral/senior-level.md',
    'behavioral/principal-level.md',
    'interview-categories-and-questions.md',
    'problem-solving-framework.md',
    'resume-and-interview-tips.md'
]

materials_en = {}
materials_pl = {}

# Read English files
for filepath in files_en:
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            materials_en[filepath] = content
            print(f"✓ Loaded EN: {filepath}")
    except FileNotFoundError:
        print(f"✗ Not found: {filepath}")
    except Exception as e:
        print(f"✗ Error reading {filepath}: {e}")

# Read Polish files (with .pl.md extension)
for filepath in files_en:
    # Convert path to Polish version
    if filepath.endswith('.md'):
        filepath_pl = filepath[:-3] + '.pl.md'
    else:
        filepath_pl = filepath + '.pl'

    try:
        with open(filepath_pl, 'r', encoding='utf-8') as f:
            content = f.read()
            # Use same key as English version for easy lookup
            materials_pl[filepath] = content
            print(f"✓ Loaded PL: {filepath_pl}")
    except FileNotFoundError:
        # If Polish version doesn't exist, use English as fallback
        if filepath in materials_en:
            materials_pl[filepath] = materials_en[filepath]
            print(f"⚠ Using EN as fallback for: {filepath_pl}")
    except Exception as e:
        print(f"✗ Error reading {filepath_pl}: {e}")

# Generate JavaScript file with bilingual structure
js_output = """// Materials data - Auto-generated file (Bilingual: EN/PL)
// Generated by generate-materials-data.py
// This file contains all markdown content embedded for offline use

// Use window for browser, fallback to global for Node.js
(function(global) {
    const MATERIALS_DATA = {
        en: """

js_output += json.dumps(materials_en, indent=4, ensure_ascii=False)

js_output += """,
        pl: """

js_output += json.dumps(materials_pl, indent=4, ensure_ascii=False)

js_output += """
    };

    // Export to global scope
    global.MATERIALS_DATA = MATERIALS_DATA;

    // Also export for Node.js if available
    if (typeof module !== 'undefined' && module.exports) {
        module.exports = MATERIALS_DATA;
    }
})(typeof window !== 'undefined' ? window : global);
"""

# Write to file
with open('materials-data.js', 'w', encoding='utf-8') as f:
    f.write(js_output)

print(f"\n✅ Generated bilingual materials-data.js")
print(f"📦 EN: {len(materials_en)} files")
print(f"📦 PL: {len(materials_pl)} files")
print(f"📦 Total size: {len(js_output) / 1024:.2f} KB")
